Fixing OCP checks for rh-1.0
aquasecurity/kube-bench pull request #1259
Opened 2022-08-24 10:35 UTC by anupamtamrakar

OCP checks were failing because error in audit commands

Also, updated couple of checks text to remove 'Automated' as their type was manual

Please note, there are multiple other checks exist where description text keyword has (Manual) but doesn't have any type

We will plan to update them after discussion

Please review @josedonizetti @chen-keinan @deven0t

2022-09-05 14:09 UTC, mozillazg requested changes

2022-09-05 14:09 UTC, mozillazg commented on cfg/rh-1.0/master.yaml
> +        text: "Ensure that the etcd pod specification file ownership is set to root:root (Manual)"
Should update the value of `scored` field to `false` if it should be `Manual`.

2022-09-05 14:09 UTC, mozillazg commented on cfg/rh-1.0/node.yaml
> +        text: "Ensure that the --authorization-mode argument is not set to AlwaysAllow (Manual)"
Ditto.

2022-09-05 14:09 UTC, mozillazg commented on cfg/rh-1.0/node.yaml
> +        text: "Ensure that the kubeAPIQPS [--event-qps] argument is set to 0 or a level which ensures appropriate event capture (Manual)"
Ditto.

2022-09-12 13:11 UTC, mozillazg commented on cfg/rh-1.0/master.yaml
> +        text: "Ensure that the etcd pod specification file ownership is set to root:root (Manual)"
I mean this field:
<img width="911" alt="image" src="https://user-images.githubusercontent.com/485054/189661641-5551d403-1605-4873-bb9c-2e5fc8762e13.png">

2022-09-14 01:00 UTC, mozillazg approved these changes
LGTM, Thanks for your contribution!

2022-09-14 14:20 UTC, chen-keinan commented
@anupamtamrakar please rebase with upstream

2022-09-14 14:21 UTC, chen-keinan approved these changes

2022-10-10 19:31 UTC, chen-keinan commented
@anupamtamrakar need another rebase

2022-10-11 06:18 UTC, merged