Adding eks-stig-kubernetes-v1r6
aquasecurity/kube-bench pull request #1266
Opened 2022-08-30 02:02 UTC by crenzoaws

Closes #1247

2022-09-05 14:27 UTC, mozillazg commented
@crenzoaws Thanks for your contribution! I'll review it when I have free time. Would you please update the document at https://github.com/aquasecurity/kube-bench/blob/main/docs/platforms.md to include this new benchmark?

2022-09-07 16:12 UTC, crenzoaws commented
@mozillazg 
- The update to https://github.com/aquasecurity/kube-bench/blob/main/docs/platforms.md is included. 
- Submitted another commit to fix the lint errors identified in the previous check

2022-09-10 13:05 UTC, mozillazg commented
@crenzoaws Thanks for your update. I'll review it later.

2022-09-10 14:07 UTC, mozillazg requested changes
Thanks for your contribution! Added some comments please check again, thanks!

2022-09-10 14:07 UTC, mozillazg commented on hack/kind-stig.test.yaml
> +          image: docker.io/aquasec/kube-bench:5c76890
```suggestion
          image: docker.io/aquasec/kube-bench:latest
```

2022-09-12 17:24 UTC, crenzoaws commented on hack/kind-stig.test.yaml
> +          image: docker.io/aquasec/kube-bench:5c76890
Updated

2022-09-12 17:24 UTC, crenzoaws commented on cfg/eks-stig-kubernetes-v1r6/node.yaml
> +        text: "Ensure that the kubelet configuration file has permissions set to 644 or more restrictive (Automated)"
Updated

2022-09-12 17:24 UTC, crenzoaws commented on cfg/eks-stig-kubernetes-v1r6/node.yaml
> +        text: "Ensure that the kubelet kubeconfig file ownership is set to root:root (Automated)"
Updated

2022-09-12 17:24 UTC, crenzoaws commented on cfg/eks-stig-kubernetes-v1r6/node.yaml
> +        text: "Ensure that the --hostname-override argument is not set (Automated)"
Updated

2022-09-12 17:25 UTC, crenzoaws commented on cfg/eks-stig-kubernetes-v1r6/node.yaml
> +        text: "Ensure that the --authorization-mode argument is not set to AlwaysAllow (Automated)"
Updated

2022-09-12 17:25 UTC, crenzoaws commented on cfg/eks-stig-kubernetes-v1r6/node.yaml
> +        text: "Ensure that the --authorization-mode argument is not set to AlwaysAllow (Automated)"
Updated

2022-09-12 17:26 UTC, crenzoaws commented on cfg/eks-stig-kubernetes-v1r6/node.yaml
> +        text: "Ensure that the --protect-kernel-defaults argument is set to true (Automated)"
Updated

2022-09-12 17:27 UTC, crenzoaws commented on cfg/eks-stig-kubernetes-v1r6/node.yaml
> +        text: "Ensure that the --anonymous-auth argument is set to false (Automated)"
Update test and moved to controlplane.yaml along with test - V-242400 The Kubernetes API server must have Alpha APIs disabled (Automated)

2022-09-12 17:28 UTC, crenzoaws commented on cfg/eks-stig-kubernetes-v1r6/node.yaml
> +        text: "Ensure that the --read-only-port argument is set to 0 (Manual)"
Updated

2022-09-12 17:30 UTC, crenzoaws commented on cfg/eks-stig-kubernetes-v1r6/controlplane.yaml
> +  - id: 2.2
As a result of moving other tests to controlplane.yaml a group 2.1 was created to represent DISA Category Code I tests. This was left as is to represent DISA Category Code II tests.

2022-09-12 17:30 UTC, crenzoaws commented on cfg/eks-stig-kubernetes-v1r6/controlplane.yaml
> +        text: "Enable audit logs (Manual)"
Updated

2022-09-12 17:32 UTC, crenzoaws commented
@mozillazg - Thanks for all your feedback. I've incorporated all the changes you've identified.

2022-09-13 13:19 UTC, crenzoaws commented
Upstream dependency failure:  sgerrand/alpine-pkg-glibc#185

2022-09-13 13:31 UTC, crenzoaws commented
Upstream package error: sgerrand/alpine-pkg-glibc#185

2022-09-14 00:54 UTC, mozillazg commented
> @mozillazg - Thanks for all your feedback. I've incorporated all the changes you've identified.

Thanks for your patience. It looks like the `integration/testdata/Expected_output_stig.data` file needed to be updated too.

2022-09-14 14:37 UTC, mozillazg approved these changes
LGTM, Thanks for your contribution!

2022-09-14 14:40 UTC, chen-keinan approved these changes

2022-09-14 14:40 UTC, merged