Added empty op val and non-empty flagName test
aquasecurity/kube-bench pull request #1517
Opened 2023-10-31 09:52 UTC by arjunkhunti-crest

2023-11-05 09:16 UTC, mozillazg reviewed
Could you please fix the e2e test? Thanks.

2023-11-07 13:48 UTC, mozillazg requested changes

2023-11-18 07:50 UTC, arjunkhunti-crest commented on check/test.go
> +					if t.Compare.Op == "eq" && !strings.Contains(t.Flag, ":") {
I'm not familiar with the process of adding a new operation, and I'm thinking about closing this pull request. I'll communicate this process in the corresponding issue to encourage others to contribute instead.

2023-11-18 07:52 UTC, arjunkhunti-crest commented
As the suggested approach is different as implemented in this PR. Hence closing this PR.

2023-11-18 07:52 UTC, closed without merging