FIX| RKE-CIS-1.24- CHECK 1.1.19
aquasecurity/kube-bench pull request #1722
Opened 2024-11-05 04:06 UTC by sm171190

The check #1.1.119 of rke-cis-1.24 benchmarks relies on a helper audit script that is not present in the Kube-Bench file system. As a result this check results in a file not found error.
We have added the contents of this script(https://github.com/rancher/security-scan/blob/master/package/helper_scripts/check_files_owner_in_dir.sh) as the audit command for this check, ensuring that we are checking the same directory as the original check.

2024-11-07 16:17 UTC, deven0t commented on cfg/rke-cis-1.24/master.yaml
> -        audit: "check_files_owner_in_dir.sh /node/etc/kubernetes/ssl"
we 3 code places where I see this script usage. 
can we try making it available as script and copy them in docker image.

2024-11-12 06:20 UTC, deven0t commented on Dockerfile
> +COPY helper_scripts/check_files_owner_in_dir.sh /go/bin
better to have this step before we define entrypoint for better readability. we can put next to other copy commands

2024-11-12 10:19 UTC, deven0t approved these changes

2024-11-14 06:13 UTC, afdesk commented
hi @sm171190 @deven0t 

I can see this mistake in [the check 1.1.19](https://github.com/aquasecurity/kube-bench/blob/main/cfg/rke-cis-1.24/master.yaml#L273-L275).

2024-11-14 06:23 UTC, afdesk requested changes

2024-11-14 06:23 UTC, afdesk commented on helper_scripts/check_files_owner_in_dir.sh
why do we need to copy/paste this script? 
maybe does it make sense to download the script directly from the source?
wdyt?

2024-11-14 06:29 UTC, afdesk commented
just to confirm, Do i understand correctly, `Dockerfile.ubi` and `Dockerfile.fips.ubi` aren't updated, because there is no any case for RKE CIS and these images, right? thanks!

2024-11-14 06:43 UTC, sm171190 commented on helper_scripts/check_files_owner_in_dir.sh
I think it's better that the script goes packaged with Kube-Bench. wherever one goes, the other csn be guaranteed to be available. And if there are users whose cluster is in an air-gapped env or in a vpc with stringent inbound rules downloading may not even be an option. But this way we are still guaranteed to have the script available. Whatsay? Plu, aesthetically speaking - it improves the structure of Kube-Bench too I feel. Later, we can add our own cusom scripts that replace rpeated actions from multiple audits of other checks. That's my 2 cents. @deven0t ?

2024-11-14 06:45 UTC, sm171190 commented
> just to confirm, Do i understand correctly, `Dockerfile.ubi` and `Dockerfile.fips.ubi` aren't updated, because there is no any case for RKE CIS and these images, right? thanks!

No. This was an accidental omission from my end. We should also make the same change in ubi images. Will update

2024-11-14 07:24 UTC, afdesk commented on helper_scripts/check_files_owner_in_dir.sh
I meant maybe we can use `wget`/`curl` inside Dockerfile to download the script from sources.
my concern is we have to keep this one up to date manually now

2024-11-15 09:39 UTC, afdesk approved these changes

2024-11-15 11:31 UTC, deven0t approved these changes

2024-11-15 12:32 UTC, merged