Update Readme.md file with Licensing and Proper Documentation links
aquasecurity/kube-bench pull request #754
Opened 2020-10-22 05:49 UTC by kaiwalyakoparkar

- [x]  Added the License agreement
- [x] Added the more efficient links to the issues so that they do not break when they are forked.
- [x] Added the year and the owner name in the license agreement

2020-10-29 11:04 UTC, lizrice requested changes

2020-10-29 11:04 UTC, lizrice commented on README.md
> +Please encourage and support all the contribution to this project. Kindly read [Contributing.md](CONTRIBUTING.md) before contributing. Some instructions for the common contributions are stated below.
```suggestion
Kindly read [Contributing.md](CONTRIBUTING.md) before contributing. Some instructions for the common contributions are stated below.
```

Deleted the first sentence as it's not clear who it's aimed at (contributors or maintainers?) I do like the addition of a link to the Contributing page.

2020-11-01 05:04 UTC, kaiwalyakoparkar commented on README.md
> +Kindly read [Contributing.md](CONTRIBUTING.md) before contributing. Some instructions for the common contributions are stated below.
@lizrice  I have made changes as requested. Kindly review these changes.

2020-11-02 10:28 UTC, lizrice requested changes
Thanks for the changes, this is nearly there, but please note we REALLY don't want any changes to do with licensing. At all!

2020-11-02 10:28 UTC, lizrice commented on README.md
> +This entire project comes with a Apache License, Version 2.0. Kindly read it [here](LICENSE)
Please remove this, we don't need to duplicate the information that's already covered by License

2020-11-23 18:53 UTC, lizrice approved these changes
lgtm

2020-12-08 17:17 UTC, merged