Add a total summary and always show all tests.
aquasecurity/kube-bench pull request #759
Opened 2020-10-29 10:06 UTC by czunker

Whether the total summary is shown can be specified with an option.

Fixes #528

Signed-off-by: Christian Zunker <christian.zunker@codecentric.cloud>

2020-10-29 20:22 UTC, lizrice reviewed
Thanks for your work on this so far! I also commented on #528 with a suggestion about how to present the sections that are skipped.

2020-10-29 20:22 UTC, lizrice commented on cmd/common.go
> +			colors[check.WARN].Printf("== Remediations %s==\n", r.Type)
Nice addition

2020-10-29 20:22 UTC, lizrice commented on cmd/master.go
> +		runChecks(check.MASTER, filename, !isMaster())
This should always attempt to run regardless of node type, because the user has explicitly asked for the master tests

2020-10-29 20:22 UTC, lizrice commented on cmd/node.go
> +		runChecks(check.NODE, filename, false)
Same comment as for master, if the user expicitly tries to run the node test cases we should make an attempt

2020-10-29 20:22 UTC, lizrice commented on cmd/root.go
> +		isMasterNode := isMaster()
Can you explain your thinking on changing this logic here? I think I preferred all the decisions about whether to skip a section here in one place, but perhaps I am missing something?

2020-11-09 11:02 UTC, lizrice requested changes
I'd just like to change some of the stdout output into logs (see the suggestions) but otherwise this looks good, thank you!

2020-11-09 11:02 UTC, lizrice commented on cmd/root.go
> +			fmt.Println("== Skipping master checks ==")
Let's keep these as log output

2020-11-09 11:03 UTC, lizrice commented
@yoavrotems @danielpacak note that when we merge this, it will change the default JSON output to include overall totals

2020-11-09 13:55 UTC, czunker commented
Hi @lizrice ,
changed the output according to your suggestions.

2020-12-06 13:20 UTC, yoavrotems commented
@czunker Hey I fixed some conflicts and now the PR seems to fail the tests

2020-12-07 16:50 UTC, czunker commented
Hi @yoavrotems ,

rebased to master and fixed the first issue.
It seems, there was a closing bracket missing:
https://github.com/aquasecurity/kube-bench/pull/759/commits/75e5aa9c0a4b5f260b7a1038f5775d31e703e78d#diff-f3346ecefc99144b92b77b4e6ae336aafbd52a75b9587e026ce0325162fc7afdR709

No some results fail in the integration tests. Correcting the numbers. That just than pass the integration test.

2020-12-08 10:20 UTC, lizrice approved these changes
lgtm

2020-12-08 10:21 UTC, merged