Fix 1.1.7 1.1.8 for KOPS
aquasecurity/kube-bench pull request #798
Opened 2021-01-13 13:16 UTC by DOboznyi

In KOPS used etc-manager which bootstrap 2 etcd clusters: main and event. So i changed logic and it check all manifests which contain etcd in naming in `/etc/kubernetes/manifests`.
Signed-off-by: Dmytro Oboznyi <dmytro.oboznyi@syncier.com>

2021-01-13 14:32 UTC, DOboznyi commented
@yoavrotems Could you review this PR?

2021-01-18 09:10 UTC, yoavrotems commented
Its a bit too restrictive to my opinion, we are using config.yaml to be less fixed and more flexible, but now it could cause to someone who use config.yaml to add is own custom yaml that doesn't include etcd in the name or even include etcd but has caps "myEtcdForDev.yaml" it will fail the test.
better solution could be to maybe add option to have "AND" in config.yaml currently its like "OR", having AND could work with it like "use_multiple_values" flag, then all the standard config will still and the custom won't fail because we check for a specific pattern in file name.

2021-01-18 09:10 UTC, yoavrotems requested changes
Look at the comment above ^

2021-01-18 11:20 UTC, DOboznyi commented
The main problem for me that kube-bench test only first found entry from configuration file and i can't there some pattern for search...

2021-01-19 08:59 UTC, yoavrotems approved these changes
Ok I see what you saying, since it doesn't effect any existing values in config.yaml it will be fine to merge it

2021-01-20 12:42 UTC, merged